import type { Team } from "./types"

export const initialTeams: Team[] = [
  {
    id: "1",
    name: "barbudonipon",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "2",
    name: "blayde99",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "3",
    name: "bow",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "4",
    name: "B.4.B.1.",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "5",
    name: "EsseAza",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "6",
    name: "ExtranoGabu",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "7",
    name: "J.rain",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "8",
    name: "Kaede_Monthmore",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "9",
    name: "PhOeNiX_H",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "10",
    name: "SWisleyTTV",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
  {
    id: "11",
    name: "victor_fujita",
    photo: null,
    rodadas: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golsSofridos: 0,
  },
]
