import type { Team } from "./types"

export const initialTeams: Team[] = [
  {
    id: "1",
    name: "Flamengo",
    photo: null,
    rodadas: 10,
    vitorias: 7,
    empates: 2,
    derrotas: 1,
    golsMarcados: 20,
    golsSofridos: 8,
  },
  {
    id: "2",
    name: "Palmeiras",
    photo: null,
    rodadas: 10,
    vitorias: 7,
    empates: 1,
    derrotas: 2,
    golsMarcados: 18,
    golsSofridos: 9,
  },
  {
    id: "3",
    name: "Botafogo",
    photo: null,
    rodadas: 10,
    vitorias: 6,
    empates: 2,
    derrotas: 2,
    golsMarcados: 15,
    golsSofridos: 7,
  },
  {
    id: "4",
    name: "Atletico-MG",
    photo: null,
    rodadas: 10,
    vitorias: 5,
    empates: 3,
    derrotas: 2,
    golsMarcados: 14,
    golsSofridos: 10,
  },
  {
    id: "5",
    name: "Sao Paulo",
    photo: null,
    rodadas: 10,
    vitorias: 5,
    empates: 2,
    derrotas: 3,
    golsMarcados: 13,
    golsSofridos: 11,
  },
  {
    id: "6",
    name: "Fluminense",
    photo: null,
    rodadas: 10,
    vitorias: 4,
    empates: 3,
    derrotas: 3,
    golsMarcados: 12,
    golsSofridos: 10,
  },
]
